x-user: &default-user
  # --- UID y GID del usuario host --------------------------
  user: "${UID:-1000}:${GID:-1000}"
  environment:
    # Algunos scripts de Composer / NPM usan estas vars
    PUID: "${UID:-1000}"
    PGID: "${GID:-1000}"

services:
  # ──────────────────────────────── PHP / FPM ─────────────
  erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macasa_erp
    restart: always
    volumes:
      - ./:/var/www/html:cached
    <<: *default-user          # 👈  corre con tu UID/GID
    depends_on:
      - mariadb
    networks:
      - macasa-red-docker

  # ──────────────────────────────── Nginx ─────────────────
  nginx:
    image: nginx:latest
    container_name: macasa_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:cached
    depends_on:
      - erp
    networks:
      - macasa-red-docker

  # ──────────────────────────────── MariaDB ───────────────
  mariadb:
    image: mariadb:10.6
    container_name: macasa_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: erp_ecommerce_db
      MYSQL_USER: macasa_user
      MYSQL_PASSWORD: macasa123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - macasa-red-docker

networks:
  macasa-red-docker:
    external: true

volumes:
  mariadb_data:
    name: mariadb_data
